```yaml
title: "Lise Verlaet : Vers une intelligence technologique et une science ouverte"
categories:
  - Science Ouverte
  - Humanités Numériques
  - Éditorialisation
  - Constructivisme
  - Web Sémantique
```

## Lise Verlaet
[{{< fa brands github >}} GitHub](https://www.idref.fr/127453865) [{{< fa brands github >}} GitHub](https://orcid.org/0000-0002-3909-0184) [{{< fa brands github >}} GitHub](https://hal.science/search/index/?q=authIdHal_s:lise-verlaet) 


[Page Institutionnelle](https://www.univ-montp3.fr/) | [HAL](https://hal.archives-ouvertes.fr/) | [NumeRev](https://numerev.com/)

**Résumé**
Lise Verlaet interroge les mutations structurelles de l'édition scientifique à l'ère du numérique, en mettant l'accent sur les modèles de l'Open Access et l'éditorialisation des données. À travers le prisme du constructivisme et de la systémique, elle analyse comment les dispositifs socio-techniques (web sémantique, plateformes de savoir) redéfinissent la production et la circulation des connaissances. Son approche interdisciplinaire vise à renforcer l'intelligence collective et la démocratisation des savoirs face aux enjeux technopolitiques actuels.

**Résonances Bibliographiques**

*   **L'économie politique de la publication scientifique :** Une exploration des modèles d'affaires de l'Open Access (notamment via le projet NumeRev) et des enjeux de l'édition scientifique qui lient démocratie et accessibilité des savoirs.
*   **Épistémologie du numérique et Constructivisme :** Une critique de la "technoscience" qui dépasse l'outil pour penser le numérique comme système constructiviste, influençant la cognition et la gestion du capital humain.
*   **Structuration et Sémantisation des connaissances :** L'apport fondamental du Web de données et du balisage sémantique pour transformer l'information brute en un écosystème de connaissances évolutives et interopérables au service des Humanités Numériques.