```yaml
---
title: "Médiations Numériques et Transformations Organisationnelles : Santé, Éducation et Société"
categories:
  - "Communication Organisationnelle"
  - "Santé Numérique"
  - "Littératie de l'IA"
  - "Innovation Sociale"
---
```

## Michel Durampart
[{{< fa brands github >}} GitHub](https://www.idref.fr/060850728) [{{< fa brands github >}} GitHub](https://hal.science/search/index/?q=authIdHal_s:michel-durampart) 


[Google Scholar](https://scholar.google.com/scholar?q=Michel+Durampart)

**Résumé**
Les travaux de Michel Durampart interrogent les mutations des organisations sous le prisme des technologies de l'information et de la communication. En articulant santé, éducation et médiation sociale, il analyse comment l'intégration du numérique — de l'IA à la télémédecine — reconfigure les pratiques professionnelles, l'acculturation des usagers et la responsabilité sociale des structures. Ses recherches mettent en lumière les enjeux de la littératie numérique au sein d'organisations apprenantes en constante adaptation.

**Résonances Bibliographiques**

*   **Innovations Technologiques en Santé :** *Binding communication to improve peripheral venous catheter monitoring* ; *IA et lecture de tissu prostatique* ; *Programme de recherche Clinique*.
*   **Éducation et Littératie Numérique :** *Ce que former à l’IA peut/veut dire* ; *Panorama des recherches sur éducation et numérique : acculturation et forme scolaire* ; *Apprentissage à distance et e-learning*.
*   **Dynamiques Organisationnelles et RSE :** *Régulation et médiation organisationnelles* ; *Communication organisationnelle et « Responsabilité Sociale des Entreprises »* ; *Informations et services*.
*   **Culture, Société et Réseaux :** *Représentation(s) et Numérique(s)* ; *La colaboración científica en línea* ; *Industries culturelles et innovation frugale*.