```yaml
---
title: "Nouria Harbi : Sécurité des Données et Analyse de la Véracité"
categories:
  - Data Warehouse
  - Cybersecurity
  - Cloud Computing
  - Social Media Intelligence
---
```

## Nouria Harbi
[{{< fa brands github >}} GitHub](https://www.idref.fr/18011915X) 


**Liens** : [Google Scholar](https://scholar.google.fr/scholar?q=Nouria+Harbi)

**Résumé**
Expertiser la donnée sous l'angle de sa protection et de sa fiabilité constitue le cœur des travaux de Nouria Harbi. Ses recherches s'articulent principalement autour de la sécurisation des entrepôts de données (notamment dans le Cloud) via des contrôles d'accès contextuels et la gestion des inférences. En parallèle, elle développe des approches d'apprentissage automatique pour la détection d'intrusions et l'analyse multimodale de la véracité des rumeurs sur les réseaux sociaux.

**Résonances Bibliographiques**

*   **Sécurisation des Entrepôts de Données et Cloud**
    *   La confidentialité des entrepôts de données dans le cloud computing : Etat de l’art et perspectives
    *   Contrôle d’accès aux entrepôts de données fondées sur le profil utilisateur
    *   Securing Data Warehouses: A Semi-automatic Approach for Inference Prevention at the Design Level
    *   Secret sharing for cloud data security: a survey
    *   MODELING CONFLICT OF INTEREST IN THE DESIGN OF SECURE DATA WAREHOUSES

*   **Intelligence Artificielle et Détection d'Intrusion**
    *   Real detection intrusion using supervised and unsupervised learning
    *   An Efficient Fuzzy Clustering-Based Approach for Intrusion Detection
    *   A New Supervised Learning Algorithm Using Naive Bayesian Classifier
    *   Enhancing Data Security through Comprehensive Traceability: A Labeling Approach

*   **Analyse des Médias Sociaux et Véracité de l'Information**
    *   Vers une analyse de la véracité des rumeurs basée sur les images issues des réseaux sociaux : état de l'art