```yaml
---
title: "Orélie Desfriches Doria : Modélisation des Connaissances et Esprit Critique"
categories:
  - Organisation des Connaissances
  - Humanités Numériques
  - Controverses
  - Éducation aux Médias
---
```

## Orélie DESFRICHES DORIA
[{{< fa brands github >}} GitHub](https://www.idref.fr/178282154) 


[Université Paris 8 - Laboratoire Paragraphe]

**Résumé**  
Les travaux d'Orélie Desfriches Doria articulent les sciences de l'information avec les enjeux de la culture numérique. Elle explore la structuration des savoirs via les classifications à facettes tout en interrogeant la circulation des discours médiatiques et scientifiques. Ses recherches promeuvent la modélisation et la cartographie des controverses comme leviers pédagogiques essentiels au développement de l'esprit critique.

**Résonances Bibliographiques**

*   **Organisation des Connaissances et Design de l'Information**
    *   *La classification à facettes pour la gestion des connaissances métier*
    *   *De l'usage à la forme : le design pour créer du sens*
    *   *Miipa-Doc : gestion de l'hétérogénéité des classifications documentaires*

*   **Controverses, Argumentation et Esprit Critique**
    *   *La modélisation cartographique des controverses, un outil au service de l’esprit critique ?*
    *   *Analyser une controverse écologique sur YouTube*
    *   *Réflexions sur l'évolution des formes et des structures argumentatives*

*   **Humanités Numériques et Circulation des Savoirs**
    *   *What is Digital Humanities' identity in interdisciplinary practices?*
    *   *« Publicize or Perish » : nouvelles formes de circulation et d'évaluation des savoirs*
    *   *Communiquer sur l’archivage : réalisation d’un guide des bonnes pratiques*

*   **Éducation aux Médias et Usages des Écrans**
    *   *Recherche-action en EMI : Éducation aux écrans et implication des parents*
    *   *Santé, jeunes et écrans : une analyse de la circulation des discours médiatiques*
    *   *Contexte d’usages des écrans en plein Covid-19*