```yaml
title: "Philippe Bonfils : Les Métamorphoses de la Justice Pénale et des Mineurs"
categories:
  - Droit pénal
  - Justice des mineurs
  - Procédure pénale
  - Droits de l'homme
```

## Philippe Bonfils
[{{< fa brands github >}} GitHub](https://www.idref.fr/052595269) 


**Liens :** [Google Scholar](https://scholar.google.com/scholar?q=Philippe+Bonfils) | [Cairn](https://www.cairn.info/resultats_recherche.php?searchTerm=Philippe+Bonfils)

**Résumé**  
Philippe Bonfils se distingue par une expertise approfondie du droit pénal, articulant la rigueur de la procédure générale avec les spécificités protectrices de la justice des mineurs. Ses travaux interrogent la fonction éducative de la peine et l'évolution de la responsabilité pénale, tout en revisitant les fondements humanistes de la matière, notamment à travers l'héritage de Beccaria. Pédagogue et théoricien, il analyse également les mutations contemporaines du droit pénal des affaires et le rôle crucial de la défense.

**Résonances Bibliographiques**

*   **L'Enfance face à la Justice : Protection et Sanction**
    *   *Droit des mineurs*
    *   *La fonction éducative de la peine*
    *   *Le droit pénal substantiel des mineurs*
    *   *Réforme du droit pénal des mineurs*
    *   *Non-information de disparition de mineur de quinze ans*

*   **Architecture et Pratique de la Procédure Pénale**
    *   *Droit pénal général*
    *   *Les grands arrêts de la procédure pénale [11e édition]*
    *   *Guide de l'avocat commis d'office : 2022-2023*
    *   *Commentaire de textes juridiques, arrêts et jugements*

*   **Droit Pénal Spécial et Fondements Théoriques**
    *   *Droit pénal des affaires : cours & travaux dirigés*
    *   *L'influence de Cesare Beccaria sur la matière pénale moderne*
    *   *Le pseudonyme entre personnalité et propriété : un signe distinctif en quête de statut*
    *   *Loi n° 2007-1598 du 13 novembre 2007 relative à la lutte contre la corruption*