```yaml
---
title: "Renée Bourassa : Simulation, Magie et Édition Numérique"
categories:
  - Humanités numériques
  - Muséologie
  - Avatar
  - Post-vérité
  - Édition
---
```

## Renée Bourassa
[{{< fa brands github >}} GitHub](https://www.idref.fr/060604344) 


**Liens**

*   [Université Laval - profil chercheur](https://www.flsh.ulaval.ca/)
*   [Laboratoire des nouvelles technologies de l'image, du son et de la scène](https://lantiss.ulaval.ca/)

**Résumé**

Renée Bourassa interroge les frontières poreuses entre le réel et la simulation à travers le prisme des arts médiatiques et des humanités numériques. Ses travaux explorent la "magicalité" des technologies, depuis la sémiotique des avatars et les effets de présence jusqu'aux mutations structurelles du livre et de l'édition. Elle analyse en profondeur les enjeux de l'authenticité face aux puissances du faux, reliant les arts trompeurs à l'ère de la post-vérité.

**Résonances Bibliographiques**

*   **Illusions et simulacres technologiques**
    *   *Machines. Magie. Médias.*
    *   *Magicalité, simulation et intelligence artificielle : formes et enjeux des puissances contemporaines de l'illusion*
    *   *Le réel à l'épreuve des technologies*
    *   *Des arts trompeurs à la post-vérité. Puissances du faux et stratégies de tromperie*

*   **Avatars et présences numériques**
    *   *Figures de l’avatar : agents semi-autonomes, effets de présence et interpellation dans les jeux vidéo*
    *   *La capture de mouvement*
    *   *Le Sujet Digital*

*   **Édition et matérialités du savoir**
    *   *Devenirs numériques de l’édition*
    *   *Version 0. Notes sur le livre numérique*
    *   *Espace liminaire de l’authenticité : Une démarche d’humanités numériques*