```yaml
---
title: "Matérialités et pédagogies du récit interactif"
categories: [Littérature numérique, Narrativité, Pédagogie, Éditorialisation]
---
```

## Serge Bouchardon
[{{< fa brands github >}} GitHub](https://www.idref.fr/101521693) [{{< fa brands github >}} GitHub](https://orcid.org/0000-0002-4430-7130) [{{< fa brands github >}} GitHub](https://hal.science/search/index/?q=authIdHal_s:serge-bouchardon) 

[Page chercheur](https://www.costech.utc.fr/) | [Publications](https://hal.science/)

**Résumé**
Les travaux de Serge Bouchardon se situent au croisement de la sémiotique, de la création artistique et des sciences de l'information. Il explore les spécificités du "faire" numérique, analysant comment la gestualité et l'interactivité transforment la narration littéraire (IDN). Sa recherche s'étend pragmatiquement à l'éditorialisation en libre accès et à la didactique de la littérature numérique dans l'enseignement secondaire.

**Résonances Bibliographiques**
*   **Poétique et Matérialité** : Une exploration des tensions entre dispositif technique et sens, mettant l'accent sur la spécificité gestuelle (*Towards Gestural Specificity*) et la temporalité (*Digital Narrative and Experience of Time*) dans l'expérience de lecture.
*   **Didactique du Numérique** : Une série d'études sur l'intégration des récits interactifs dans le secondaire français, positionnant la littérature numérique comme vecteur de nouvelles compétences de littératie (*IDNs in Education*, *Teaching Literary Interactive Digital Narratives*).
*   **Traduction et Transposition** : Analyse des défis uniques posés par la traduction d'œuvres littéraires programmées, où le code et la culture s'entremêlent (*Traversing Boundaries When Translating a Literary IDN*).
*   **Stratégies Éditoriales** : Réflexion sur l'évolution des modèles éditoriaux pour les sciences humaines et la création en ligne (*Un dispositif innovant d’éditorialisation*, *Création littéraire en ligne*).