---
title: "L'analogie du geste : Frontières mouvantes de la littératie numérique"
author: Serge Bouchardon
categories: [Littérature numérique, Écriture numérique, Sémiotique, Éditorialisation]

subtitle: "L'analogie à l'épreuve du discret : Le jugement humain face à la décision calculée"
bibliography: "../referenceAuteurs.bib"



---

#### University of Technology of Compiègne Université de technologie de Compiègne
[{{< fa solid globe >}} https://www.idref.fr/101521693](https://www.idref.fr/101521693) [{{< fa solid globe >}} https://orcid.org/0000-0002-4430-7130](https://orcid.org/0000-0002-4430-7130) [{{< fa solid globe >}} https://hal.science/search/index/?q=authIdHal_s:serge-bouchardon](https://hal.science/search/index/?q=authIdHal_s:serge-bouchardon) 


::: {.callout-note appearance='minimal'}
**Résumé :** Les travaux de Serge Bouchardon explorent la matérialité de l'écriture numérique et les frontières poreuses entre le texte et le code, redéfinissant les dispositifs d'éditorialisation [@valluy:hal-03790580]. En analysant les récits interactifs et leur intégration pédagogique [@bouchardon:hal-03091085], il interroge comment la sémiotique du geste technique participe à la construction du sens au sein des environnements numériques.
:::

### Proposition générée

  - [lien vers les données](https://humanum-p8.fr/paragraphe/s/valorisations/item/59842)
  - [lien vers le prompt](prompt_serge_bouchardon.txt)
  - [lien vers la réponse](resume_serge_bouchardon.json)



**Titre : L'analogie du geste : Manipuler les frontières du récit interactif**

**Résumé :**
Cette intervention se situe principalement dans l'**Axe 2 (L’Analogie comme outil cognitif)** et l'**Axe 4 (Limites, Éthique et Créativité)**. Elle propose d'analyser la littérature numérique non plus seulement comme un texte à lire, mais comme un système d'analogies opératoires où le geste du lecteur (cliquer, scroller, toucher) devient une métaphore performative de l'action narrative. Contrairement à la métaphore statique du bureau ou de la page [@Delannay2025], l'œuvre numérique interactive crée une "analogie procédurale" qui remet en question la frontière entre le langage et l'outil [@LeroiGourhan1964]. En s'appuyant sur ses recherches en création littéraire et en pédagogie, l'auteur démontrera comment ces dispositifs déplacent les frontières de la littératie, transformant l'écran d'une simple paroi en une zone de "prise" et de "déprise" cognitive, nécessitant une nouvelle éthique de l'interprétation face à la manipulation algorithmique.

### Résonances Bibliographiques

La proposition de Serge Bouchardon entre en résonance directe avec plusieurs ouvrages clés de la conférence :

*   **Frontières et Éditorialisation :** L'approche de Bouchardon sur les dispositifs d'éditorialisation en SHS [@valluy:hal-03790580] fait écho à la vision de [@Noyer2016] pour qui les frontières sont des zones fluctuantes nécessitant de nouveaux dispositifs éditoriaux, ainsi qu'à [@Debray2013] définissant la frontière comme un filtre régulateur plutôt qu'un mur.
*   **Analogie et Apprentissage :** Ses travaux sur l'enseignement de la littérature numérique [@bouchardon:hal-03091085] dialoguent avec la thèse de [@HofstadterSander2013], considérant l'analogie comme le moteur central de l'apprentissage et de l'extension des catégories cognitives.
*   **Geste et Outil :** En traitant l'écriture numérique comme un acte technique autant que linguistique, Bouchardon réactualise le parallélisme fondamental entre le langage et l'outil théorisé par [@LeroiGourhan1964].
*   **Interopérabilité des sens :** La question de la traduction et du passage des frontières dans les récits interactifs ("Traversing Boundaries") illustre parfaitement le concept de [@Citton2010] de la frontière comme passerelle assurant une communication non triviale.