project:
  type: website

website:
  title: "Frontières Numériques 2026"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Accueil
      - href: auteurs.qmd
        text: Intervenants

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    from: markdown+emoji