```yaml
title: "Dramaturgie des Avatars et Scènes Hybrides"
categories:
  - Théâtre
  - Motion Capture
  - Avatar
  - Réalité Mixte
  - Recherche-Création
```

## Georges Gagneré
[{{< fa brands github >}} GitHub](https://www.idref.fr/071395016) [{{< fa brands github >}} GitHub](https://orcid.org/0000-0002-3930-1236) 


**Liens :**
[Archives HAL](https://cv.hal.science/georges-gagnere) | [Didascalie.net](http://www.didascalie.net/)

**Résumé :**
Georges Gagneré explore les frontières poreuses entre la scène théâtrale et les arts numériques, se focalisant spécifiquement sur la direction d'avatars et l'usage de la capture de mouvement en temps réel. À travers une démarche de recherche-création, il développe des outils technologiques (AKN_Regie) et des protocoles artistiques pour intégrer le double numérique comme partenaire de jeu dans un espace de réalité mixte.

**Proposition d'intervention :**
*Titre : L'Ombre Numérique : Analogie du Geste et Dédoublement de l'Acteur*

Dans le cadre de *Frontières Numériques 7*, cette intervention interrogera l'analogie entre l'acteur physique et son "ombre" numérique (l'avatar). Comment la technologie de la motion capture, en traduisant le mouvement biologique en données numériques, crée-t-elle une nouvelle forme de marionnette virtuelle qui s'émancipe de son modèle ? Nous analyserons comment la "direction d'avatar" oblige le metteur en scène à repenser la présence scénique, transformant la contrainte technique (latence, prévisualisation) en une esthétique du dédoublement et de la spectralité.

**Résonances Bibliographiques :**
*   *Acteur et avatar : vers une dissolution de l'acteur dans les écrans ?* (Questionnement ontologique sur la place de l'humain).
*   *Mises en scène spectaculaires et interactives de l’avatar* (Approche pratique des technologies de temps réel).
*   *The Wizard without Shadow* (Étude de cas sur l'invisibilité et la projection virtuelle).
*   *AKN_Regie : une passerelle entre arts numériques et spectacle vivant* (L'outil comme médiateur technologique).