```yaml
title: "Imad Saleh : Architectures collaboratives et frontières de l'hypertexte"
categories:
  - Bibliothèques numériques
  - Crowdsourcing
  - Hypertexte
  - Web sémantique
```

## Imad SALEH

[Lien vers les publications](http://bbf.enssib.fr/contributions/lacorrection-participative-de-l-ocr-par-crowdsourcing-au-profit-des-bibliotheques-numeriques-0)

**Résumé**

Les travaux d'Imad Saleh interrogent la structuration de l'information numérique, évoluant de l'hypertexte sémantique vers des écosystèmes collaboratifs et l'Internet des objets. En analysant la transformation des bibliothèques numériques par le crowdsourcing et l'automatisation, il explore la perméabilité des "frontières numériques". Son approche met en lumière la mutation des dispositifs d'apprentissage et de médiation, où la technologie ne se contente plus de stocker le savoir, mais le dynamise par l'intelligence collective.

**Proposition d'intervention**

*Titre : De la page au flux : Analogies de la médiation dans les écosystèmes collaboratifs*

Cette intervention pour *Frontières Numériques 7* propose d'examiner l'analogie entre les structures traditionnelles du savoir (la bibliothèque, la frontière géographique) et leurs réincarnations technologiques (le web sémantique, l'espace collaboratif). Imad Saleh analysera comment les technologies de l'hypertexte et du crowdsourcing redéfinissent la notion de "correction" et de "validité" de l'information. En s'appuyant sur l'exemple de la correction participative de l'OCR, il démontrera que la technologie n'est pas une simple rupture, mais une analogie fonctionnelle de l'intelligence collective, transformant l'utilisateur passif en acteur structurel de la mémoire numérique. L'intervention questionnera in fine si l'Internet des objets constitue une simple évolution technique ou une refonte ontologique de nos interactions avec le réel.

**Résonances Bibliographiques**

*   **Sur l'hybridation humain-machine :** Andro M., Saleh I. (2015) “La correction participative de l’OCR par crowdsourcing au profit des bibliothèques numériques”, Bulletin des bibliothèques de France.
*   **Sur la mutation des objets techniques :** Bouhaï N. et Saleh I. (2017) “Internet des objets : évolution ou révolution”, ISTE.
*   **Sur la structure de l'information :** "Hypertextualisation automatique : Approche structurelle pour la construction des réseaux navigables".
*   **Sur le cadre théorique :** "Perspectives scientifiques des frontières numériques".