---
title: Youssef MEKOUAR
categories:
  - CNN
  - LSTM
  - IoT
  - Smart-City
  - Data-visualization
  - Environment
  - CO2
  - Connected Objects
subtitle: "De l'Index Sémantique au Jumeau Numérique : Visualiser l'Invisible Urbain"
bibliography: referenceAuteurs.bib


---

#### Laboratoire paragraphe
[{{< fa solid globe >}} https://www.idref.fr/268466238](https://www.idref.fr/268466238) [{{< fa solid globe >}} https://orcid.org/0009-0001-9493-9777](https://orcid.org/0009-0001-9493-9777) 


::: {.callout-note appearance='minimal'}
**Résumé :** Les travaux de Youssef Mekouar se situent à l'intersection de l'ingénierie des données et de la visualisation sémantique. Il explore notamment les méthodes de visualisation augmentée pour la structuration de connaissances scientifiques [@mekouar:hal-03469855], tout en appliquant des modèles d'intelligence artificielle (hybrides CNN-LSTM) et l'IoT pour la modélisation et la cartographie des émissions de CO2 dans les environnements urbains complexes [@mekouar:hal-05196080].
:::

### Proposition générée

  - [lien vers les données](https://humanum-p8.fr/paragraphe/s/valorisations/item/1102)
  - [lien vers le prompt](prompt_youssef_mekouar.txt)
  - [lien vers la réponse](resume_youssef_mekouar.json)



**Titre : De l'Index Sémantique au Jumeau Numérique : Visualiser l'Invisible Urbain**

**Résumé :**
Cette intervention propose d'explorer l'analogie entre la navigation dans les corpus documentaires massifs et la compréhension des flux environnementaux urbains. En s'appuyant sur les technologies de visualisation augmentée initialement développées pour les index sémantiques, nous montrerons comment ces principes peuvent être transposés à la "lecture" de la ville intelligente. La présentation détaillera comment les modèles hybrides d'apprentissage profond, utilisés pour prédire les taux de CO2, transforment des données brutes et invisibles en une cartographie interactive et intelligible. Nous analyserons comment la technologie agit ici comme une lentille analogique, convertissant les métriques abstraites de l'IoT en représentations spatiales concrètes, permettant ainsi de révéler les dynamiques écologiques cachées de la ville de Paris et d'offrir de nouvelles interfaces pour la décision publique.

### Résonances Bibliographiques

Les recherches de Youssef Mekouar illustrent une double approche de la frontière numérique : celle de la représentation de la connaissance et celle de la modélisation du réel. Son travail sur la visualisation augmentée [@mekouar:hal-03469855] pose les bases d'une interface cognitive permettant d'appréhender la complexité sémantique. Cette approche résonne directement avec ses applications dans le domaine des *Smart Cities*, où la carte interactive du trafic et des émissions de CO2 [@mekouar:hal-05196080] devient un outil de médiation. Ces travaux lient l'abstraction algorithmique (CNN, LSTM) à la matérialité des enjeux climatiques, démontrant comment les technologies de l'information construisent des analogies fonctionnelles pour rendre le monde physique plus lisible.