---
title: Khaldoun ZREIK
categories:
  - Post-Numérique
  - Smart Heritage
  - HyperUrbain
  - Conception
  - BIM
  - Humanités Numériques

bibliography: referenceAuteurs.bib

---

#### Khaldoun ZREIK
[{{< fa solid globe >}} https://www.idref.fr/030064880](https://www.idref.fr/030064880) [{{< fa solid globe >}} https://orcid.org/0000-0002-6307-1717](https://orcid.org/0000-0002-6307-1717) 


::: {.callout-note appearance='minimal'}
**Résumé :** Khaldoun Zreik interroge les mutations de la conception et de l'organisation des connaissances à l'ère du post-numérique [@zreik:hal-04440493; @zreik:hal-04440700]. Ses recherches lient l'évolution de l'HyperUrbain et des interactions humaines médiatisées [@zreik:hal-04436908] aux enjeux de préservation du patrimoine via le *Smart Heritage* et l'analyse de données [@bouhai:hal-04427437; @torresyepez:hal-04450093].
:::

### Proposition

**Titre : Du Smart au Post-Numérique : Analogies d'une mémoire urbaine**

Dans le cadre de *Frontières Numériques 7*, cette intervention propose d'explorer le passage de la *Smart City*, souvent réduite à une approche technocentriste, vers la ville post-numérique où la technologie devient une couche ambiante et invisible. En mobilisant les concepts d'HyperUrbain et de *Smart Heritage*, nous analyserons l'analogie entre la structuration des données architecturales (BIM, IFC) et la préservation de la mémoire patrimoniale immatérielle. Il s'agira de débattre de la capacité des technologies numériques à agir comme des supports cognitifs de conception et de médiation, tout en questionnant les risques de "biopiraterie" des savoirs traditionnels et la falsifiabilité du document numérique. Cette approche vise à redéfinir la relation Homme-Territoire non plus comme une simple interface de commande, mais comme un écosystème d'analogies sensibles entre le passé reconstitué et un futur hyper-connecté.

### Résonances Bibliographiques

Les travaux de Khaldoun Zreik s'articulent autour de plusieurs pivots thématiques essentiels aux frontières numériques :

*   **L'ère Post-Numérique et la Ville :** La transition de la ville intelligente vers une "Data City" post-numérique est centrale [@zreik:hal-04440700]. Zreik questionne la temporalité et la conception dans ce nouveau paradigme où le numérique est omniprésent [@zreik:hal-04440493], prolongeant ses réflexions antérieures sur la dématérialisation du territoire [@zreik:hal-04436908].
*   **Patrimoine et Humanités Numériques :** L'ouvrage *Smart Heritage* [@bouhai:hal-04427437] pose les bases d'une réflexion sur l'hybridation entre technologies (BIM, Réalité Virtuelle) et conservation culturelle. Cette approche critique s'étend aux risques éthiques, notamment la biopiraterie des savoirs dans l'espace numérique [@torresyepez:hal-04450093].
*   **Méthodologies et Pédagogies Innovantes :** L'analyse algorithmique et la visualisation de données sont explorées comme leviers pour comprendre les pédagogies alternatives [@torresyepez:hal-04450083], faisant écho aux premiers travaux sur la créativité à l'ère de l'hypermédia [@zreik:hal-01011841].