---
title: Michel Durampart
categories:
  - Technologies de l'information et de la communication
  - Apprentissage
  - IA
  - organisation apprenante
  - innovation frugale

bibliography: referenceAuteurs.bib

---

#### Michel Durampart
[{{< fa solid globe >}} https://www.idref.fr/060850728](https://www.idref.fr/060850728) [{{< fa solid globe >}} https://hal.science/search/index/?q=authIdHal_s:michel-durampart](https://hal.science/search/index/?q=authIdHal_s:michel-durampart) 


::: {.callout-note appearance='minimal'}
**Résumé :** Michel Durampart explore les mutations des dispositifs communicationnels, allant des enjeux de la littératie numérique face à l'IA [@collet:halshs-04772108] aux nouvelles formes de récits en Sciences de l'Information et de la Communication [@durampart:hal-04394316]. Ses travaux interrogent également les représentations au sein des interfaces numériques [@collet:hal-03211193] et l'innovation pédagogique dans des contextes institutionnels variés [@pelissier:hal-02466230].
:::

### Proposition

Dans le cadre de "Frontières Numériques 7 : Analogies & Technologies", je propose d'interroger la fonction analogique du "prompt" dans les interactions homme-machine, en analysant comment l'instruction textuelle tente de modéliser une intention créative ou pédagogique. En m'appuyant sur les expériences de "classe renversée" et d'intégration de l'IA dans les formations en communication, cette intervention questionnera la frontière entre la compétence technique et la réflexivité critique. Il s'agira de démontrer comment les technologies actuelles, loin d'être de simples outils, reconfigurent la structure même du récit et de la représentation. Nous analyserons si l'analogie entre l'intelligence humaine et artificielle, souvent promue par les interfaces, résiste à l'épreuve des pratiques pédagogiques et des réalités institutionnelles, proposant ainsi une nouvelle lecture de l'acculturation numérique.

### Résonances Bibliographiques

Cette proposition s'articule autour de la nécessité de redéfinir la littératie numérique à l'ère de l'intelligence artificielle, en examinant comment les dispositifs de formation peuvent dépasser l'instrumentalisation pour atteindre une véritable réflexivité critique [@collet:halshs-04772108]. Elle entre en résonance directe avec les questionnements sur l'évolution du récit et son inscription épistémologique en SIC, suggérant que la technologie agit comme un nouveau narrateur ou co-auteur [@durampart:hal-04394316]. Par ailleurs, cette approche critique des interfaces et de leurs représentations [@collet:hal-03211193] permet de lier ces enjeux théoriques aux dynamiques concrètes d'innovation et d'incubation au sein des organisations apprenantes [@pelissier:hal-02466230].