---
title: Olivier Nannipieri
categories:
  - Réalité virtuelle
  - Réalité augmentée
  - Présence
  - Immersion
  - Environnements immersifs
  - Phénoménologie
  - Mesure
bibliography: referenceAuteurs.bib
---

#### Olivier Nannipieri
[{{< fa solid globe >}} https://www.idref.fr/177559748](https://www.idref.fr/177559748) [{{< fa solid globe >}} https://hal.science/search/index/?q=authIdHal_s:olivier-nannipieri](https://hal.science/search/index/?q=authIdHal_s:olivier-nannipieri) 


::: {.callout-note appearance='minimal'}
**Résumé :** Les travaux d'Olivier Nannipieri interrogent la complexité de l'expérience utilisateur au sein des environnements virtuels et augmentés, en se focalisant sur la conceptualisation et la mesure de la « présence ». Il analyse les limites des échelles psychométriques traditionnelles [@nannipieri:hal-04404674] tout en explorant la tension phénoménologique entre le réel et le virtuel [@nannipieri:hal-04396912]. Ses recherches s'étendent également aux applications de la réalité augmentée dans des contextes marketing et ludiques [@muratore:hal-01453221].
:::

### Proposition

**Titre provisoire : La réalité du virtuel : Analogie de la présence et limites de la mesure**

Dans le cadre de *Frontières Numériques 7*, cette intervention propose d'explorer l'analogie entre la présence physique et la présence médiatisée, non comme une simple équivalence, mais comme une construction phénoménologique complexe. En s'appuyant sur une critique des outils de mesure actuels [@nannipieri:hal-04404674] et sur la modélisation de l'absence dans les environnements virtuels [@nannipieri:hal-03175298], nous questionnerons la capacité des technologies à créer une « réalité » signifiante pour l'utilisateur. L'intervention mobilisera la taxonomie fonctionnelle de la réalité augmentée [@fuchs:hal-00536787] pour illustrer comment les dispositifs techniques ne se contentent pas de superposer des données, mais restructurent notre rapport au monde. L'objectif est de dépasser le paradoxe technique pour comprendre les mécanismes cognitifs et sensoriels qui fondent l'immersion [@nannipieri:hal-04396912], redéfinissant ainsi les frontières entre l'être-là et l'être-connecté.

### Résonances Bibliographiques

Les recherches d'Olivier Nannipieri s'articulent autour de la tension entre la sophistication technologique des dispositifs et la réalité subjective de l'expérience vécue :

*   **Critique de la métrologie immersive :** L'auteur remet en cause la validité des questionnaires standards pour capturer l'essence de l'expérience immersive, suggérant une approche par équations structurelles pour mieux cerner les déterminants de la présence [@nannipieri:hal-04404674].
*   **Phénoménologie du virtuel :** En co-écriture avec Jacques Ghoul Samson, il propose de dépasser la dichotomie réel/virtuel pour envisager la « réalité du virtuel » sous un angle phénoménologique, où l'image et la signification priment sur la matérialité [@nannipieri:hal-04396912].
*   **Hybridation des espaces :** Ses travaux antérieurs sur la taxonomie de la réalité augmentée [@fuchs:hal-00536787] et l'expérience ludique en RA [@muratore:hal-01453221] ancrent ces réflexions théoriques dans l'analyse concrète des dispositifs qui modifient notre perception de l'espace et de l'interaction.