---
title: Alessandro Leiduan
categories: [Fiction, Smart City, Esthétique, Transmédialité, Mondes imaginaires, Cybernétique]

subtitle:"La Smart City comme récit cybernétique : analogies esthétiques et fictions urbaines"
bibliography: referenceAuteurs.bib



---


[{{< fa solid globe >}} https://www.idref.fr/096205121](https://www.idref.fr/096205121) 


::: {.callout-note appearance='minimal'}
**Résumé :** Alessandro Leiduan interroge les mutations de la narration contemporaine en formulant une critique de la raison narrative à l'heure du numérique [@leiduan:hal-04604631]. Ses recherches croisent philosophie et sciences de l'information pour analyser l'esthétique des environnements technologiques comme la *Smart City* [@leiduan:hal-04176102], tout en explorant la structuration des mondes imaginaires au travers des dispositifs transmédiatiques [@roux:hal-04217767].
:::

### Proposition

**Titre : La Smart City comme récit cybernétique : analogies esthétiques et fictions urbaines**

**Résumé :**
Cette intervention propose d'explorer la *Smart City* non pas comme une simple accumulation d'infrastructures technologiques, mais comme une construction esthétique et narrative majeure du XXIe siècle. En s'appuyant sur une approche critique de la "raison narrative", nous analyserons comment la ville connectée opère une analogie fonctionnelle entre la gestion des données et le storytelling, transformant l'espace urbain en un décor transmédia où le citoyen devient l'acteur d'une fiction algorithmique. Nous questionnerons la dimension sensible de cette technologie : comment l'esthétisation des flux de données modifie-t-elle notre jugement de goût (au sens kantien) sur la ville ? Entre promesse d'efficacité cybernétique et réalité d'un contrôle narratif, nous démontrerons que la technologie urbaine agit comme un puissant générateur de mythes modernes.

### Résonances Bibliographiques

L'œuvre d'Alessandro Leiduan offre une perspective critique essentielle pour les *Frontières Numériques*, articulant les technologies de l'information avec les structures de l'imaginaire.

*   **Narrativité et Numérique :** Dans sa *Critique de la raison narrative* [@leiduan:hal-04604631], l'auteur établit une analogie entre les processus cognitifs de mise en récit et les logiques computationnelles, suggérant que le numérique ne se contente pas de diffuser des histoires, mais en modifie la structure profonde.
*   **Esthétique de la Technologie :** Son analyse de la *Smart City* [@leiduan:hal-04176102] permet de penser la technologie urbaine comme un objet esthétique, résonnant avec les thématiques de l'interface et de la perception sensible des frontières numériques.
*   **Immersion et Transmédia :** L'étude des *Mondes imaginaires et univers transmédiatiques* [@roux:hal-04217767] prolonge cette réflexion en montrant comment les écosystèmes fictionnels contemporains utilisent la fragmentation technologique pour créer des totalités cohérentes, brouillant la frontière entre le réel et le virtuel.