---
title: "De la Smart City à l'HyperUrbain : L'analogie comme résilience dans l'ère Post-Numérique"
author: Khaldoun Zreik
categories: [Post-Numérique, HyperUrbain, Smart Heritage, Conception, Humanités Numériques]

subtitle: "De la Smart City à l'HyperUrbain : L'analogie comme résilience dans l'ère Post-Numérique"
bibliography: referenceAuteurs.bib



---

#### Laboratoire paragraphe
[{{< fa solid globe >}} https://www.idref.fr/030064880](https://www.idref.fr/030064880) [{{< fa solid globe >}} https://orcid.org/0000-0002-6307-1717](https://orcid.org/0000-0002-6307-1717) 


::: {.callout-note appearance='minimal'}
**Résumé :** 
Dans un espace logiciel défini par une « bataille des signes » [@Serres1997], les frontières numériques ne sont plus des murs mais des passerelles d'interopérabilité [@Citton2010] et des interfaces de filtrage du chaos [@Guattari1992]. En dépassant la simple analogie techniciste de l'urbanisme des SI [@BidanGode2017], nous devons concevoir ces frontières comme des zones éthologiques fluctuantes [@Noyer2016] où la technologie ne se contente pas de modéliser le réel, mais redéfinit notre ontologie relationnelle.
:::

### Proposition générée

  - [lien vers les données](https://humanum-p8.fr/paragraphe/s/valorisations/item/85479)
  - [lien vers le prompt](prompt_khaldoun_zreik.txt)
  - [lien vers la réponse](resume_khaldoun_zreik.json)



**Titre : De la Smart City à l'HyperUrbain : L'analogie comme résilience dans l'ère Post-Numérique**

**Résumé :**

Cette intervention interroge la transition de la « Smart City » vers la « Data City » et, *in fine*, vers l'ère du Post-Numérique où la technologie devient invisible et omniprésente. En nous appuyant sur le concept d'HyperUrbain, nous explorons comment l'analogie du système nerveux urbain, souvent utilisée pour justifier l'optimisation algorithmique, doit être dépassée pour inclure les dimensions affectives, patrimoniales et sociales. La frontière numérique ne sépare plus l'homme de son territoire ; elle dématérialise cette relation, créant une hybridation complexe. Face à la modélisation analogique des écosystèmes de connaissances, nous analyserons comment les dispositifs de médiation (Smart Heritage) et la conception architecturale doivent intégrer l'incertitude et la temporalité humaine pour éviter une simple réduction du citoyen à une donnée exploitable. Il s'agit de repenser la créativité et l'éthique au sein de ces nouvelles matrices territoriales pour garantir que la ville de demain reste une œuvre publique et non un monopole algorithmique.

### Résonances Bibliographiques

Les travaux de Khaldoun Zreik sur l'**HyperUrbain** et la dématérialisation de la relation Homme-Territoire [@zreik:hal-04436908] entrent en résonance directe avec la vision de la frontière comme « passoire » et régulateur proposée par **Debray** [@Debray2013]. Là où Debray théorise le filtre, Zreik observe comment les TIC et les réseaux sociaux redéfinissent physiquement et socialement l'espace urbain, transformant la frontière en une interface de médiation active.

L'analyse de la **Data City** et du **Post-Numérique** [@zreik:hal-04440700] prolonge l'analogie de l'urbanisme appliquée aux systèmes d'information évoquée par **Bidan & Godé** [@BidanGode2017]. Zreik va plus loin en suggérant que l'analogie ne sert pas seulement à concevoir le système, mais qu'elle matérialise une nouvelle forme de cité où les flux de données (Big Data) deviennent la matière première, rejoignant ainsi l'idée de **Szoniecky** [@Szoniecky2024] sur l'analogie des écosystèmes pour modéliser les connaissances.

Dans le domaine du **Smart Heritage** [@bouhai:hal-04427437], la numérisation du patrimoine culturel interroge les matrices ontologiques décrites par **Descola** [@Descola2005]. En créant des doubles numériques et des hyper-héritages, nous basculons dans une ontologie analogiste reliant les physicalités des artefacts à des intériorités numériques reconstruites, un processus qui nécessite une vigilance éthique face aux risques d'appropriation marchande soulignés par **Moulier Boutang** [@moulierboutang2010].

Enfin, les préoccupations éthiques concernant la **biopiraterie du patrimoine immatériel** [@torresyepez:hal-04450093] illustrent concrètement la « bataille des signes » de **Serres** [@Serres1997]. Il s'agit ici de protéger le sens et le sujet contre une capture abusive par les dispositifs techniques, réaffirmant la nécessité de penser le temps de la conception [@zreik:hal-04440493] non comme une simple exécution algorithmique, mais comme un processus humaniste complexe.