---
title: "L'analogie entre le corpus numérique et le corps biologique ou  comment Filtrer le chaos informationnel pour détecter le signal 'pathologique'"
author:
  - name: Marc Tanti
    affiliations:
      - name: "CESPA - Centre d'épidémiologie et de santé publique des armées, Marseille"
      - name: Institut mediterranéen des sciences de l'information et de la communication  (IMSIC)
      - name: Aix Marseille Université
  - name: Fetta Belgacem
    affiliations:
      - name: Institut mediterranéen des sciences de l'information et de la communication  (IMSIC)
      - name: Aix Marseille Université
categories: [Big Data, Santé Publique, Surveillance, Méthodologie, Textual Analysis]
subtitle: "L'analogie du symptôme : De la trace textuelle à la surveillance épidémiologique"
bibliography: referenceAuteurs.bib
---

#### Sciences Economiques et Sociales de la Santé et Traitement de l'Information Médicale

[{{< fa solid globe >}} https://www.idref.fr/15096871X](https://www.idref.fr/15096871X)

::: {.callout-note appearance="minimal"}
**Bio Marc Tanti :** MarcTANTI posséde une HDR en sciences de l’information et de la communication. Reçu à la qualification des Professeurs des Universités (CNU 71), il est Chevalier de l’ordre des palmes académiques et titulaire de la médaille pour travaux techniques et scientifiques du SSA, échelon argent. Ses travaux se situent à l’intersection de l’ingénierie des connaissances, de la santé publique et de l’analyse de données massives. Ils explorent notamment comment les institutions, y compris militaires, peuvent exploiter les mégadonnées du web social pour relever des défis méthodologiques en épidémiologie et en veille sanitaire [@belgacem:hal-04956773]. Son parcours témoigne également d’une réflexion sur la valorisation et la structuration de la recherche scientifique et technique [@Tanti2010], appliquant des méthodes mixtes à des cas concrets allant des maladies infectieuses aux troubles addictifs.
:::

::: {.callout-note appearance="minimal"}
**Bio Fetta Belgacem :** Fetta BELGACEM est docteure en sciences de l’information et de la communication. Ses travaux se situent à l’intersection des études sur l’espace publique, les réseaux sociaux numériques et les données massives. Elle est l’auteure de l’ouvrage « mobilisations sociales à l’épreuve du numérique » [@belgacem2024], publié en 2024 aux éditions l’harmattan. Elle est actuellement chercheuse postdoctorale au centre d’épidémiologie et de santé publique des armées où elle explore les données de santé du web social [@belgacem:hal-04956773] pour identifier les problématiques de santé exprimées par le personnel militaires et leurs familles.
:::

### Proposition déposée sur scienceconf.org

-   [lien vers la proposition](https://frontieresnum7.sciencesconf.org/734476)

**Titre : L'analogie entre le corpus numérique et le corps biologique ou comment Filtrer le chaos informationnel pour détecter le signal "pathologique"**

**Résumé :** Cette intervention propose d’analyser comment l’analogie entre le corps biologique et le corpus numérique transforme la veille sanitaire. En s’appuyant sur l’exploitation des mégadonnées du web social [@belgacem:hal-04956773] et à partir d'une analogie entre le corpus numérique et le corps biologique, nous démontrerons comment le texte peut devenir lui-même symptôme et signal "pathologique" faible. Cette approche nécessite la conception de méthodes capables de distinguer le bruit du signal "pathologique". Dans cette communication,nous interrogerons également les frontières méthodologiques et éthiques de cette transposition : jusqu’où peut-on assimiler les traces numériques à des marqueurs biologiques sans tomber dans un réductionnisme dangereux, transformant la veille sanitaire en un dispositif de contrôle social ?

### Résonances Bibliographiques

La démarche de Marc Tanti, qui consiste à extraire du sens sanitaire à partir du chaos des données sociales, résonne fortement avec la conception de la frontière comme "crible" chez **Guattari** [@Guattari1992], agissant comme une interface sélective entre les virtualités du chaos (le flux incessant du web social) et les potentialités actuelles (la détection d'une épidémie).

Cette extraction de signaux d'alerte s'inscrit dans la "bataille des signes" décrite par **Serres** [@Serres1997], où l'espace logiciel devient le terrain d'une lutte pour s'approprier le sens des données de santé, souvent à l'insu des émetteurs. En transformant le langage naturel en indicateur épidémiologique, Tanti illustre le parallélisme fondamental entre langage et outil évoqué par **Leroi-Gourhan** [@LeroiGourhan1964], où l'algorithme devient le prolongement technique du diagnostic médical.

Enfin, l'usage de ces méthodes par des institutions (comme les armées) pour modéliser des risques réels via des données virtuelles évoque les "matrices ontologiques" de **Descola** [@Descola2005], en créant une ontologie analogiste où les correspondances entre les mots (sur le web) et les maux (dans les corps) définissent une nouvelle frontière de la surveillance, fonctionnant non comme un mur, mais comme la "passoire" régulatrice théorisée par **Debray** [@Debray2013].