---
title: "L'écosystème et le protocole : Analogies structurantes des nouvelles frontières de l'écriture numérique"
author: Nicolas Sauret
categories: [Humanités numériques, Écriture numérique, Éditorialisation, Épistémologie du modèle, Littérature numérique]
subtitle: "Architectures de l'analogie : concevoir des écosystèmes de connaissances comme des jardins partagés"
bibliography: referenceAuteurs.bib


---

#### Laboratoire paragraphe
[{{< fa solid globe >}} https://www.idref.fr/241664284](https://www.idref.fr/241664284) [{{< fa solid globe >}} https://orcid.org/0000-0001-7516-3427](https://orcid.org/0000-0001-7516-3427) [{{< fa solid globe >}} https://hal.science/search/index/?q=authIdHal_s:nicolas-sauret](https://hal.science/search/index/?q=authIdHal_s:nicolas-sauret) 


::: {.callout-note appearance='minimal'}
**Résumé :** En s'appuyant sur l'épistémologie des modèles [@sauret:hal-03963579], cette réflexion montre comment l'analogie de l'écosystème [@szoniecky2024] structure nos environnements d'écriture numérique. En concevant des interfaces savantes comme des milieux écosophiques [@krummeich:halshs-04019870], la frontière technologique devient une passerelle opérante [@citton2010] qui redéfinit l'autorité, la collaboration et la matérialité éditoriale [@vitalirosati:hal-04336752].
:::

### Proposition générée

  - [lien vers les données](https://paragraphe.humanum-p8.fr/s/valorisations/item/85513)
  - [lien vers le prompt](prompt_nicolas_sauret.txt)
  - [lien vers la réponse](resume_nicolas_sauret.json)



**Titre : L'écosystème et le protocole : Analogies structurantes des nouvelles frontières de l'écriture numérique**

**Résumé :**
Dans le champ des humanités numériques, la conception de dispositifs d'écriture (Stylo, Pink my pad) et d'outils de découverte (ISIDORE) repose fondamentalement sur des choix analogiques qui modélisent notre rapport au savoir. Cette intervention se propose d'explorer comment les analogies de « l'écosystème » et du « protocole » redéfinissent les frontières du texte et de la recherche scientifique. En nous éloignant de la métaphore limitante de la page blanche au profit d'environnements computationnels (notebooks, gestionnaires de versions), l'écriture devient une pratique réticulaire et « écosophique ». Nous montrerons que ces nouvelles matrices analogiques ne se contentent pas d'imiter des fonctionnements biologiques ou urbains, mais agissent comme des filtres régulateurs organisant l'autorité, la littératie et l'éditorialisation collective (la « gittérature »). Ainsi, comprendre l'épistémologie de ces modèles éditoriaux permet de saisir comment les technologies construisent de nouvelles zones de contact disciplinaires, transformant la frontière numérique en un espace poreux de négociation sémantique.

### Résonances Bibliographiques

Les travaux de Nicolas Sauret s'articulent intimement avec la réflexion sur les frontières et les analogies selon plusieurs axes conceptuels majeurs de la conférence :

**1. Épistémologie et matrices analogiques :** 
La recherche de Sauret sur l'épistémologie du modèle et l'héritage d'Alan Turing [@sauret:hal-03963579] entre en résonance directe avec l'idée d'une pensée algorithmique s'inscrivant dans une ontologie analogiste telle que formulée par Serres [@serres2009] et Descola [@descola2005]. Le modèle computationnel agit ici comme un pont syntaxique et sémantique.

**2. L'écosystème comme interface et crible :**
L'appréhension des carnets de recherche (notebooks) en tant qu'objets "écosophiques" [@krummeich:halshs-04019870] et l'évolution des moteurs de recherche vers des logiques écosystémiques [@pouyllau:hal-03932033 ; @pouyllau:hal-05202136] matérialisent concrètement l'analogie des écosystèmes pour modéliser les connaissances théorisée par Szoniecky [@szoniecky2024]. Ces dispositifs fonctionnent exactement comme le crible décrit par Guattari [@guattari1992], filtrant le chaos des données pour en faire des potentialités de sens.

**3. Les frontières de l'autorité et de l'éditorialisation :**
En explorant la « gittérature » [@monjour:hal-03962836] et l'écriture collaborative numérisée à travers des outils comme Stylo ou Pink my pad [@vitalirosati:hal-04336752 ; @sauret:halshs-04471220v1], Sauret interroge les frontières de l'autorité littéraire et scientifique. Ces nouveaux espaces de co-création illustrent parfaitement la vision de Pomian [@pomian1976] d'une frontière résultant d'un équilibre social instable. De plus, ils confirment les propositions de Delannay [@delannay2025] : s'éloigner de l'analogie classique de la page permet d'ouvrir le canal et de remporter la "bataille des signes" dans l'espace logiciel, telle qu'évoquée par Serres [@serres1997]. L'écriture numérique n'est donc plus un mur, mais une passoire régulatrice [@debray2013].